# Community Handbook {.unnumbered}

NHS-R Community regularly host webinars, workshops, blogs and podcasts to share the communities knowledge, experience and often, enthusiasm, for subjects ranging from specifically technical (R, Python, git) to where data science has helped analytical problems in healthcare data.
There is always scope for trying things out with the community and the following sections are guidelines on what we have tried and is in no way a definitive list.

# Webinars

NHS-R Community host an hour long webinar through MS Teams Event on a Thursday, usually the last of the month.
Sessions are recorded and posted onto the NHS-R Community [YouTube channel](https://www.youtube.com/watch?v=668k5sBkKus&list=PLXCrMzQaI6c36jqIWc9AgHzowzZ2ak9DL) and collated together in the playlist Webinars.
Content can relate to anything healthcare (including social care) and/or R coding.
Webinars on other data science subjects like Python and Git/GitHub are also very welcome.

There is no restriction on who can attend the webinar and people can join/sign up through the [NHS-R Community website](#website).

Suggestions for webinars can be emailed to [the core development team](#contact-us).

# Workshops from volunteers

To volunteer any workshops please contact [the core development team](#contact-us).

## Introduction to R and R Studio

NHS-R Community host volunteers running the Introduction to R and R Studio course once a month via Zoom.
This usually is on the 3rd Wednesday of the month and is over two half days but is flexible to  the availability of the person leading the workshop.

Co-hosts can also attend and assist with:

* checking the chat, 
* any technical issues with the Host leaving the call (if a Host has a power cut for example and leaves the meeting it closes for everyone) and 
* it can be agreed between the host and co-host to share sections of the training.

[Materials](#training) are available in a chapter form from NHS-R Community GitHub to allow people the flexibility on what to cover in a session according to the time available.
There is enough content for 3 half days, however, most often only 2 half days (or 1 full day) is volunteered.

These courses are very popular and are often fully subscribed and have a waiting list.
We encourage people to join a full workshop as people have been offered places as people have notified they cannot attend and we also use these lists for future courses to invite people in advance of sharing publicly.

Recordings are always made available to attendees but are not always made public as recordings are already on available. 
However, if you wish to have a workshop you have led included these can be added if permission has been sought from the attendees before recordings have been started.
See section [Video Recording](#recordings) for more information.

Contributions and changes to the materials are always welcome and can be made via the GitHub repository.

## Other workshops

Workshops, other than the regular Introduction to R and R Studio, are very welcome and we've had talks from other languages (Python) as well as specific subjects like statistics.
All workshops are recorded and, unless specifically requested not to, are shared publicly.
See section [Video Recording](#recordings) for more information.

The length of a workshop can vary according to the content the person/people wish to deliver and have been 1 hour long, half a day or a whole day.

Workshop formats often include some code along or exercises.

# Podcasts

Recordings are made through a Zoom account with recordings saved to the cloud in separate channels to assist with later editing.

NHS-R Community publish through [Soundcloud](https://soundcloud.com/nhs-r-community) which is available through other podcast providers.

The latest podcast is published manually through the NHS-R Community WordPress site front page.

If you are interested in being in a podcast please contact [the core development team](#contact-us).

# Social Media

## NHS-R Slack {#slack}

[https://nhsrcommunity.slack.com/](https://nhsrcommunity.slack.com/)

The NHS-R Community use the free version of Slack to facilitate conversations between members.
Many people join the Slack group and enjoy reading the conversations without ever joining in and that's ok as this is the best place to find out what's happening with the community and a lot can be learned from others' conversations.
Because this is a free account we don't have a history of posts but they would be available if we moved to a paid account.

:::{.callout-important collapse=false appearance='default' icon=true}
## Managing own Slack accounts
- Because the Slack account is a free version people will need to manage their own accounts
- This includes any password resets, two-factor authentication security and changes of emails
- Where two accounts have been set up because of access loss, administrators can delete the unused account
- Details of who is Slack admin can be found in the pinned notice in the #general channel
:::


### Accessing the Slack

Some organisations' emails have been added to the white list but because there are so many public sector organisations it may be that you require an individual link to join. Please contact the central email [the core development team](#contact-us) for the link. 
Links that are shared are only available for several days.

It's best to use an organisational email for the group, but not necessary, and you are also able to change the email once you've joined.

### Deletion of accounts on Slack

Unfortunately with the free account we are unable to change email addresses which has affected some people when they move to a new organisation and require a password reset or use the Slack system of emailing a joining link.
However, we can delete any old account to avoid confusion to others on the Slack so they will only tag or direct message the active account.

Other than this situation, we would only ever delete an account due to [Code of Conduct](#code-of-conduct) issues.

### Slack security

Administrators on the Slack can see email addresses and we can bulk email, however, we do not and have not used emails to contact people in bulk. Emails are not visible to others on the Slack workspace but people can Direct Message (DM) and those messages are not visible to administrators. 

In line with good security principles we strongly suggest using two factor authentication for the Slack group.

::: {.callout-note}
You will need this for each Slack workspace that you have joined.
:::

## X (formerly X)

The account for X is no longer used for active content however the account will not be closed completely because account names are recycled.

## Fosstodon server on Mastodon

With the change in ownership to X and a great deal of the NHS-R Community audience moving to Mastodon an NHS-R Community account is also managed through the open source content server, Fosstodon.
This account is managed by the administrative support for NHS-R Community.

## Website {#website}

The NHS-R Community website is built using WordPress and managed through [VergeLabs](https://vergelabs.co.uk/).
We use the website to promote the NHS-R Community but also as an event management system where people can join the community events like the monthly webinars, conferences and other events.

### Joining the website

Signing up is at no cost but email addresses are visible to the maintainers of the website, VergeLabs, and also the [the core development team](#contact-us).
We do not use email addresses to bulk email and contact is only ever in relation to the event that has been signed up for or to update the member on the website, for example any changes to terms and conditions.

#### Fringe and Core membership

Access to register events is based on the membership level and the default is Fringe member.
Core memberships is available to all NHS, public sector, civil servants, volutary sector, charities and academia and allows registration to all workshops and webinars.

We also allow Core membership for anyone who has retired and was in these service and ask that you contact in advance, if possible, of your retirement and from a work address.

We restrict the numbers to workshops and so restrict places to just Core members.
Webinars though, don't have the same restrictions and so are open to both Core and Fringe members to attend the live event. 
The site automatically detects emails according to a white list that is maintained through the website and so we can add to that when notified at [the core development team](#contact-us).

#### Author membership

Authors are a status in the system given to those who have submitted a blog and this links their details with the blog.
WordPress only allows for one status so this may affect the joining of events.

#### Changes of emails on website

As emails can be changed we will periodically go through and update personal emails to Fringe from Core, particularly around events like the conference.

#### Confirming Core membership {#core-member}

If you are in a situation where you would like a Core membership but can only apply as a Fringe member (for example you cannot use your work email or will be retiring) or your account has been reset in preparation for events like the conference please contact [the core development team](#contact-us) with details of your situation.

#### Deletion of website membership

Accounts cannot be deleted by the member themselves but can be deleted by emailing us through the [unsubscribe](mailto:nhs.rcommunity@nhs.net?subject=unsubscribe) link which creates a blank email with the word `unsubscribe` in the header. No other detail is required for the email and we will confirm when the account has been deleted.

Periodically we will email to update members on information in relation the website, for example any changes to terms and conditions, and delete any accounts with emails that are not delivered.
Consequently, please always use a real email address if you want your account to stay active.

We use the [Government Notify](https://www.notifications.service.gov.uk/) system which is also available for Public Sector organisations to use.
Data is kept for 90 days and links from the emails are not tracked, however, we use Google Analytics on our published sites and books.

#### Password resets

It is possible to request a password reset, however, if this is going to an address that has changed due to organisational change or you have moved job, please contact [the core development team](#contact-us) for this to be updated manually.

#### Issues with apostrophes in emails

Unfortunately, where work email addresses have included the apostrophe in a person's surname the WordPress site prevents sign up but doesn't give a meaningful message.
We've attempted to force the system by updating the email in the back, however, this still means a person cannot access the account as functionality is impaired because of the non-standard character. 

As we understand it, this is an issue on many systems so suggest that, where work emails have provided the email with an apostrophe that an alias account is linked without it to get around this issue.

For NHS-R Community it's possible to sign up with a personal email and notify the [the core development team](#contact-us) about having your account set to [Core Member](#core-member).

# Mailing list/Newsletter

We have a free newsletter through [Substack](https://nhsrcommunity.substack.com/) which is open to view or subscribe to. 
Subscribtions are managed directly by the user with Substack but emails are viewable to the NHS-R account.

Podcasts are also connected to Substack.

# Video Recording {#recordings}

NHS-R Community have a Zoom account which is most often used for training and Microsoft Teams Events which is used for webinars.
Some events can be set up using Microsoft Teams which is managed through NHS Midlands and Lancashire Commissioning Strategy Unit.

In terms of recording, Zoom and Microsoft Teams Events only record the person speaking and their shared screen.
Microsoft Teams which is used by many NHS and Local Authorities for meetings, however, shows the videos and names of attenders which may be an issue for attenders.

## YouTube

We always intend to share recordings through YouTube publicly, however, we do respect where trainers or presenters ask specifically not to share recordings.
We are able to edit parts of videos using YouTube editing, cutting or blurring parts and will do this when notified.

All videos are first uploaded as Unlisted which means that anyone can access the video with the share link.
We ask that this link is not shared beyond the original people emailed.

If a video is not to be made public it will be moved to Private where only people can be given direct access to view the video.
This cannot be the default setting, unfortunately, as it relies upon having a Google mail and because the videos are often signed up from a work email we cannot use this functionality.

If you had access to a video that becomes Private and still require access, please contact the [central email](#contact-us) with details, and if you are happy to share a Google email then please email this, from a work email so that we can verify your details.

## Subtitles

YouTube applies automatic subtitles after a period of time of uploading but at the moment we don't currently amend those subtitles given the time it requires.
However, this is something that we would like to do in the future and this may mean we get support from community members.

We are copying Podcasts over to YouTube to include subtitles and are using [Clipchamp](https://app.clipchamp.com/signup) to tidy them.

# Blogs

We host blogs on the NHS-R Community website and are currently moving them over to a [Quarto site](https://nhsrcommunity.nhsrcommunity.com/) (in development) and we welcome contributions from anyone who wishes to write about R, health and social care, data science techniques and can be just text or can include code.
We review blogs before posting and will give feedback if there are any reasons that we can't publish.
Blogs are rarely removed so some will be out of date due to the changes in the programs like R and best practice.

Submissions for blogs can be in any format but need to be easily copied and pasted by [the core development team](#contact-us). 
For this reason pdf formats are not necessarily the easiest to share content.

Blogs can also be submitted as a Pull Request to the dedicated (in development) [Quarto website GitHub](https://github.com/nhs-r-community/nhs-r-community).

:::{.callout-important collapse=false appearance='default' icon=true}
## Alternative text
Pictures and charts can be included in the blogs and these are expected to have Alternative Text or Captions for greater accessibility.

This includes any pictures used for visual impact and not necessarily to add to the content directly.
:::

People who have submitted blogs and who have accounts on the website have their account altered to be a `Author` which shows their name in the Post and means they can amend the blog and respond to any comments.

# Coffee and coding

Coffee and coding is a group that was originally set up from NHS England and has been extended to anyone within the NHS-R Community.
Details are in the [blog](https://nhsrcommunity.com/coffee-and-code/).

In response to feedback and to assist with accessibility of these sessions, we have decided to mix up the days and times these meetings are on.
Hopefully, this will allow us to increase our reach.
We will still be running a session every two weeks, but the day will change across Wednesdays, Thursdays, and Fridays.

We strive to maintain community led content and would very much like to tailor these sessions to be useful, no matter what stage you at with your R journey.

There is a constant call to show us what you have been up to, anything you are working on, any issues you may have.
This is an opportunity to share what you have learned and to ask a wider audience how to do things. 
Get some friendly feedback and QA.
We very much want to foster this as a safe space to ask questions, get advice and create possible spin off sessions if there are specific areas to cover. 

Your input into making these sessions interactive and your feedback is critical in steering these sessions.
These are your sessions, and you have a voice as to what you would like to see.

The group is virtual and through MS Teams on the same link.
Booking is through <https://events.nhsrcommunity.com/coffee-and-code/> which generates an email with the link and a calendar invitation `ics`.
Note that the events are only for 2024.

Recordings are available through FutureNHS which is a platform that anyone can join but workspaces are sometimes restricted.
The NHS England R Community workspace where the [Coffee and Coding recordings](https://future.nhs.uk/NHSERcommunity/view?objectID=41908688) are not restricted.