# Conference {.unnumbered}

## Guidelines and tips

A reminder that all our events are covered by our [Code of Conduct](#code-of-conduct).

Successful speakers are expected to follow the following guidelines:

- if your talk changes details are emailed to [nhs.rcommunity@nhs.net](nhs.rcommunity@nhs.net) as soon as possible. 
If your talk changes substantially it may not be possible to accommodate your new talk as this hasn't been agreed through the sifting.
- you may use your own or organisation's slides.
We just ask that these are published publicly and a link shared.
- we accept various formats of presentations and offer our [own Quarto slides](https://github.com/nhs-r-community/NHSR-presentations) as templates - these are free to copy, change and reuse.
- feel free to give an introduction at the start of your talk but, particularly for participants from industry, please be brief and don't use this as an opportunity for sales.
This is because the audience often do not hold budgets and are attending the conference for the content of the talk.
More information can be found in the section on [sponsorship](#sponsor) with regard to the financing of the conference and community.
- the default is to share all recordings so please let us know if you don't want your recording to be shared on YouTube.
- if you cannot attend, for whatever reason and at any time, please do let us know as we will have some talks prepared for this eventuality or we may be able to extend breaks.
These are much easier to accommodate when we have notice to prepare and where we have to change the agenda this can help online attendees with managing their attendance.

We also offer the following advice:

- practice your talk! 
And do this a few times. 
If you would like someone from the NHS-R Community to talk through your slides (even in their draft form) do get in touch with us at [nhs.rcommunity@nhs.net](nhs.rcommunity@nhs.net).
We've had a few people in the past take us up on this offer and they've given fantastic talks.
- if you'd like to speak to someone about their experience at the conference and giving a presentation, again, please do get in touch.
- don't leave your slides to the last minute!
This is a tough one as work often takes priority but technical issues can occur and it's better to find these out with plenty of time to resolve.

:::{.callout-important collapse=false appearance='default' icon=true}
## Alternative text (important)
We ask in the pre-survey question if the presenter agrees to include alternative text in their presentations and this is a mandatory agreement.
As an open source conference we hope that people will share their presentations after the event and we can either host these in an NHS-R Community GitHub repository or link to them. 
Consequently, in line with our own requirements to be accessible we ask that every image and chart has [alternative text](#alt-text) and will offer support to those new to doing this.
:::


## A note for all attendees

Time keeping at conferences can vary slightly throughout the day and we attempt to start the sessions on time wherever possible.
However, where talks are shorter than anticipated, times will inevitably change and whilst this can be shared to the people in person we will not be able to update the online agenda.

## Abstract examples

Abstracts have been kindly shared by successful submitters to give those new to submitting abstracts an idea of what is wanted by the audience and organisers of the NHS-R Community and NHS.Pycom conferences.

These are not necessarily talks that will be acceptable for every year and we will be sharing our themes and scoring with abstract calls for conferences.
We will, most likely, be on the NHS-R Slack and can share updates there or answer questions.

### Abstract for an on-line workshop (half-day)

**Introduction to regression modelling in R** This workshop is the same one I've run several times over the last few years, for NHS-R, introducing regression and correlation analyses as analytical tools. We introduce how linear regression allows us to interpret the relationship between two variables. We then expand this to include more variables, different types (such as categorical data), and examine the outputs of models.

We discuss assessing model quality and predictive accuracy. We then introduce the Generalised Linear Model, and apply the principles of the earlier session to different kinds of data including count data and binary data. The final sections introduces how to use fitted models to predict outcomes and how that can be used.

### Abstract for a lightning talk (10 – 15 minutes)

**Strategies to reduce cognitive load when coding** The volume of code produced as a project progresses can get overwhelming for the contributors. The talk will give a high level overview of the strategies that can be employed to make code more manageable. Inspired by the Targets package, the talk will discuss the benefits of a function based approach to writing code to improve readability and visibility of the workflow. The benefits of re-using functions, writing tests to ensure the functions are working as intended, and storing functions within a code library or package. The benefits of code reviews and strategies to implement these and how to use version control to support this process. The importance of user friendly documentation incorporating readme files, data dictionaries, flow diagrams and SOPs. The presentation will highlight strategies to reduce the cognitive load on code writers, reduce time debugging and make work easier to understand and handover to colleagues. The presentation will signpost to useful packages and resources to explore the topic further.

**Did you hear? Base R is dead! Or is it?** I’ve spent most of my time in the public sector using the tidyverse, but I started learning R before the tidyverse existed (to be polite, you could call me ‘seasoned’). Recently I’ve started to write more base R code again. Why? I'll talk about how base R can do loads of neat stuff out of the box without you needing to install and update any packages (dependencies aren’t bad things per se, but can cause trouble if not managed appropriately). I'll also tell you about some recent additions, like the base pipe and lambda function notation, which demonstrate how base R is responding to the needs of the modern coder. Oh, and you can also do wacky stuff like make an interactive pixel-art creator, a persistent Tamagotchi pet, or a procedural dungeon-crawler. Note that this talk does not constitute a 'base versus tidyverse' flame war. It’s purely to appreciate the elegance of good old base R and to highlight some things it can do that you might not have realised (or like me, you forgot a long time ago).

Full details are shared: <https://github.com/matt-dray/nhs-r-2023>

### Abstract for a plenary plenary talk (20-30 minutes)

**You should blog with Quarto** One of the most sensible things I’ve done in my life is start an R blog. Not for clout or sponsorship deals (yet!), but so I can (1) write down what I’ve learnt about R and refer to it later, (2) help people who are looking for answers and (3) improve my communication skills. Why don’t you join the blogger lifestyle too? Or maybe you already blog, but you want to do it more often and on a platform that you’ll actually enjoy using. I’ll walk you through the process of setting up a blog using Quarto, the most hip publishing framework around. That’s right, you can use R to set up your blog and write posts about R. I’ll talk about how to deploy it for free and automatically with Netlify and also how you can hook it up with that domain name you bought years ago but never got around to using. As a bonus, I’ll give you some prompts for what to write about and some insider info on what’s been the most successful and most rewarding content for me in over 150 posts to date.

# RPySOC 24 Conference - call for abstracts

21 and 22 November 2024, Hall 11, ICC Birmingham

We are now inviting the submission of abstracts of presentations for inclusion in the conference programme.

## Programme

Day one – 21 November\
This will be a full day with a mixture of plenary and lightning talks.

Day two – 22\
November We will be dividing the meeting space and will run a mixture of plenary talks and lightning talks in one space and Unconference in the other space.

## Presentation categories

Please note:\
all talks will be in-person on 21 / 22 November.\
Plenary talk (20 – 30 minutes)\
Lightning talk (10 – 15 minutes)

## Book tickets

We won’t be booking tickets on behalf of presenters or volunteers and ask that you manage the tickets for the two days (it may be that you only wish to attend the day that you are helping or presenting for example).

## Workshops

We will be hosting virtual workshops throughout the year and we welcome submissions for workshops at any time. Please contact us on [nhs.rcommunity\@nhs.net](mailto:nhs.rcommunity@nhs.net) with details.

## How to submit

Please use this link: <https://www.smartsurvey.co.uk/s/RPYSOC24/> to complete the questionnaire and submit a short summary in the form of a 250-word abstract.

:::{.callout-important collapse=false appearance='default' icon=true}
## Abstract extension!

The closing date has been extended to **12 August 2024**!

The first day is sold out on tickets so if you haven't already done so please book a free ticket and then submit an abstract.

If you can't make the conference but would like to share your presentation we have regular virtual [webinar](#webinar) slots throughout the year. 
:::


The closing date for submissions is *26 July 2024*. We aim to respond by the end of August 2024.

Our conference team is on hand to help, if you have any queries, please contact us on [nhs.rcommunity\@nhs.net](mailto:nhs.rcommunity@nhs.net)

## Scoring

We're really interested in ***how*** you did your analysis. Because the *how* can be a broad subject in coding we are also interested in learning the tools through you. Previous successful speakers have kindly agreed to share their abstracts which we’ve posted in the NHS-R Way <https://nhsrway.nhsrcommunity.com/conference.html> and give you an idea of what we are looking for in an abstract.

Scoring criteria will be scored anonymously so please try to avoid as many personal details as possible, including any GitHub links.

Scoring this year is being tried out and is the first time that it has been shared as abstracts have been called for. Looking at the examples, we’d suggest that these would need to be adjusted slightly for this year to take these criteria into account and be explicit in how they cover the three points.

+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
| Criteria                                                                                                                                                                                                                                                       | points       |
+================================================================================================================================================================================================================================================================+==============+
| **Does the talk use, refer to or show R, Python, git or another open-source language or program that can be freely and openly used?**                                                                                                                          | 2 points     |
|                                                                                                                                                                                                                                                                |              |
| We are looking for clear explanations on what techniques were used.                                                                                                                                                                                            |              |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
| **Is this relevant to health and social care?**                                                                                                                                                                                                                | 2 points     |
|                                                                                                                                                                                                                                                                |              |
| Even if this is a talk from a different domain how would you suggest its relevant to this audience?                                                                                                                                                            |              |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+
| **Does this talk cover principles of Reproducible Analytical Pipelines – is generalisable, code first, can be replicated by others or does it cover principles or techniques of RAP?**                                                                         | **2 points** |
|                                                                                                                                                                                                                                                                |              |
| If you are new to RAP check out this great site dedicated to it in the [NHS RAP Community of Practice](https://nhsdigital.github.io/rap-community-of-practice/introduction_to_RAP/what_is_RAP/)                                                                |              |
|                                                                                                                                                                                                                                                                |              |
| The chapters summarise what we’d like to see: modular/reusable code, transparency, open-source tools, version control, good coding practices, testing and peer review. Any part of this list would be of interest and you don’t have to refer to every point.  |              |
+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+--------------+

We considered other criteria but wanted to make the system straightforward as possible for those submitting and also reviewing. The scoring points were also kept to a minimum but if we have many more abstracts than possible slots we may increase these points to give us more scope to help with accepting abstracts.

If you want any help with writing your abstract do get in touch with us at [nhs.rcommunity\@nhs.net](mailto:nhs.rcommunity@nhs.net).

## Sifting of abstracts

As for 2023 we have received more abstracts than potential slots for talks in 2024 so we had 2 groups of sifting which was necessary due to the quality of the abstracts.
The scoring was very close and was based on mean average to 2 decimal points (because some scored 0 if there was a declaration of interest by reviewers).

Because some Committee members had experience of the HACA conference abstracts where they had scored a given number of abstracts and felt this was harder to score, all abstracts were shared with the scorers.
As for HACA and previous NHS-R/NHS.pycom conferences, abstracts were shared without any detail of who had submitted leaving only the title and the abstract content.

## Two stage sifting

The first scoring had 3 scorers and they scored in their own time.

After this scoring the abstracts were shared with another 3 scorers who happened to be different people and they met for one hour to run through the scoring and decided on the cut off point according to the number of slots we have available.

The process was:

-	All lightning and plenary with mean average of greater than 5 were initially set as accepted
-	Because there were much more plenary than lightning it was decided to replace some lightning with plenary for balance in the agenda
-	Recommendations were made for talks that were felt to be better suited to longer or shorter talks or unconference style (both accepted and not accepted) 

## Final check

As the chair for the Committee, Zoë Turner, was not involved in the abstract two stage sifting she was able to check over the abstract decisions as a last check.
This involved taking the Excel spreadsheet into R and filtering to the top 29.

29 reflected a draft conference agenda of:
Day 1 - 9 lightning talks  
Day 1 - 6 plenary  

Day 2 - 7 lightning talks
Day 2 - 7 plenary 

(subject to change)

## Declaring interest

For both scoring groups we asked people to declare their interests in an abstract on the basis of:

- you should not score your own abstract
- you should not score an abstract from your team

Whilst we stripped the abstracts of identifiable information provided as part of the survey we weren't able to remove that from the abstracts themselves (particularly where people refer to their team/organisation/project or R packages).
Therefore we also asked scorers to:

- please consider the extent of bias you have if you recognise the abstract content

We found that having at least 3 scorers for each group (totalling 6) gave us enough volunteers to get a wide range of opinions for the scoring, allowed for many declarations of interest and was flexible where people found their work commitments meant they can no longer contribute to the scoring.

## Timescales

We intended to have the scoring done within 2 weeks from sending the abstracts.

## Notification of acceptance

We sent out all emails to notify people of acceptance or decline on the same day.

It was always our intention to offer the possibility of hosting a talk that had not been accepted through a virtual event and, given the high quality of the talks, this was encouraged in the email:

> However, as your abstract would be of great interest to the NHS-R Community **we'd really love to host your talk virtually**, at a time that is convenient to you and which we can share through our recordings on our [YouTube channel](https://www.youtube.com/c/nhsrcommunity) which has over 2.5k subscribers from around the world.
> This is a wonderful opportunity for us to hear your talk either at its original submitted timing of 10 or 20 minutes, or as an extended 1 hour webinar, which we host throughout the year.

## Scoring update

Feedback on the scoring was that the points given for the question:

**Does this talk cover principles of Reproducible Analytical Pipelines – is generalisable, code first, can be replicated by others or does it cover principles or techniques of RAP?**

were difficult to apply as it wasn't clear if this meant `contributing to RAP` or was `RAP`.
Where abstracts didn't necessarily score on this section they still appeared to be great abstracts.

We were unable to review this section of scoring in the timescales.

## Tickets

Although we'd been quite clear that people would be responsible for getting their tickets before submitting an abstract we found a considerable number had not booked, a smaller number also only had booked one date.

This may be because the sales of tickets peaked around the same time as the abstract deadlines were also occurring so people were unable to secure their tickets.

As we had held back tickets for conference organisers or staff required for things like Audio Visual support, we had enough tickets to offer those who were successful in their abstracts for both days if required.
This will also help with flexibility needed in theming the sessions.

## Public sharing of recordings and presentations

NHS-R Community and NHS.Pycom are committed to openly sharing their materials as much as possible. 
However, we have had requests in the past to not share parts of talks or presentations and these have been accommodated. 
Please let us know on the abstract form if you have any particular requirements in relation to not sharing and this can changed at any point up to publishing.

For materials we do strongly ask you present on open analysis and share your presentation as it’s a common question in the conference as people will want to see your work! 
Again, we are mindful that this isn’t always possible so if you cannot share your work please do consider alternative ways of sharing like using dummy data or snippets of code. 
If you need any support in publishing in the open do not hesitate in getting in touch with [nhsr.community\@nhs.net](mailto:nhs.rcommunity@nhs.net).

## Sponsorship {#sponsor}

NHS-R Community and NHS.pycom do not receive centralised funding so please get in touch if you would like to talk to us about sponsorship for holding a stand or if your presentation includes any marketing pitches.

## Administration

### Tickets

We have a ticket system in place through our website and to help with the administration of signing people in at an in-person event we have used QR codes and a Shiny app.
This worked extremely well in 2023 for the 2-day conference and all the code is available to use through [GitHub](https://github.com/nhs-r-community/conf-23-checkin) under an MIT licence.

### Submitted slides and code

Repositories for code and slides were available for years: [2019](https://github.com/nhs-r-community/Conference_2019), [2020](https://github.com/nhs-r-community/Conference_2020) and [2022](https://github.com/nhs-r-community/conference-2022).

In [2023](https://github.com/nhs-r-community/conference-2023) analysis code was used to check that abstract reviewers did not receive their own abstracts to check.

### Videos

All videos are loaded to YouTube and are only minimally edited and are collected together into the conference year playlist.

Subtitles are generated automatically by YouTube and may contain errors.

Timestamps are entered manually to the videos.