# Our Community

The NHS-R Community started in 2018 to promote the use of R in the NHS and the community has grown rapidly ever since. It is a community that is broader than the NHS as members come from public sector organisations across the UK, including Local Authorities and Civil Service, as well as academics and voluntary sector people who have an interest in healthcare. Whilst R is a core language for support by the community, there is always support for data science tools more generally, particularly where they cross over with R.

Documentation is important in coding to show methodology as well as intention so the NHS-R Community Way, inspired from [The Turing Way](https://the-turing-way.netlify.app/index.html#), is our attempt to write about the Community.

The NHS-R Community Way reflects our:

* values
* activities
* above all the community

Everything here is available for free under a CC-BY licence. Please use and re-use whatever you need, for any purpose and all the book is collaboratively written and open from the start. To make this book and the community truly accessible to everyone, we invite you to contribute your skills and bring your perspectives into this project. Write and issue, do a pull request or even [NHS-R Community](mailto:nhs.rcommunity@nhs.net). 

The NHS-R Community initially received funding for its activities but is now completely reliant upon volunteers. There is no restriction to who you work for, what your background is or what skills you have as we are the sum of all our parts and the more diverse and varied we are, the better our work together will be. 

The NHS-R Community is now hosted by the Strategy Unit, part of NHS Lancashire Midlands & Lancashire Commissioning Support Unit, which includes some administrative support, the hosting of an @nhs.net email and two data scientists roles with NHS-R Community in their job descriptions. Over the years the NHS-R Community has been involved in many activities from blogs to podcasts. 

We value the participation of every member of our community and want to ensure that every contributor has an enjoyable and fulfilling experience. Accordingly, everyone who participates in the NHS-R Way project is expected to show respect and courtesy to other community members at all times. All contributions must abide by our code of conduct.