# NHS-R vision {.unnumbered}

As a community, our overarching aim is to promote the use of R and open analytics in Health and Care.

## Using R in research

The NHS, as one of the largest hospital and healthcare systems, is a world leader in research. 
Research and evaluation are carried out as funded projects as well as unfunded audits/ evaluation. 
Both of which often require statistics - the analysis often being done in SPSS/ SAS or Excel. 
These methods can produce flawed analyses which, moreover, are not reproducible. 

Many trusts do not employ statistics experts and will only be able to get statistical help on funded work by buying in time from academic/external statisticians. 
This means that the pilot work that clinicians do prior to applying for large grants can often be flawed, or promising work ends up not being completed and the grants never awarded because they didn't have the statistics expertise.

While we would not expect clinicians to become expert coders, the NHS-R community should work to develop and deliver training that would help clinicians to be able to use R, including the development of training specifically for those with a clinical/ non coding background. 
This training needs to include R for statistics as well as the more commonly included data wrangling and visualisation.

Better collaboration between R users working in academia and those in the NHS would also be beneficial.

## Training

The NHS-R Community has developed/is developing training, with many of the workshops being made available on the NHS-R Community YouTube channel and course material available on its [GitHub](https://github.com/nhs-r-community). 

## Development 

The NHS-R Community comprises members with a very wide diversity of job roles and skills. 
Although there is no one route to being a skilled and useful analyst/data scientist/R or python developer in health and social care, nonetheless the NHS-R Community could usefully contribute to supporting recruitment, training and development of those who use R and other open code approaches to data science and analysis. 

